DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
	`userId`  int(11) NOT NULL AUTO_INCREMENT,
	`email` varchar(50) DEFAULT NULL, 
	`mobile` varchar(20) DEFAULT NULL,
	`password` varchar(50) NOT NULL, 
	PRIMARY KEY(`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE USER AUTO_INCREMENT=1000000000;

LOCK TABLES `USER` WRITE;
INSERT INTO `USER` (`password`, `email`, `mobile`)
	VALUES
	(MD5("123456789"), NULL, NULL),
	(MD5("40f9a78812345678"), NULL, NULL);
UNLOCK TABLES;


